services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: chess-frontend
    image: chess-frontend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chess
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_URL_INTERNAL=http://web:3000
      - NEXTAUTH_SECRET=supersecret
      - BACKEND_URL=http://backend:3001

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: chess-backend
    image: chess-backend
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chess
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_URL_INTERNAL=http://web:3000
      - NEXTAUTH_SECRET=supersecret

  ws:
    build:
      context: .
      dockerfile: apps/ws/Dockerfile
    container_name: chess-websocket
    image : chess-ws
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chess
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_URL_INTERNAL=http://web:3000
      - NEXTAUTH_SECRET=supersecret

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess

  migrate:
    build:
      context: .
      dockerfile: packages/db/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chess

volumes:
  postgres_data :