name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------- FRONTEND --------
      - name: Build & Push chess-web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: parthjadhao/chess-web:latest

      # -------- BACKEND --------
      - name: Build & Push chess-backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: parthjadhao/chess-backend:latest

      # -------- WEBSOCKET --------
      - name: Build & Push chess-ws
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/ws/Dockerfile
          push: true
          tags: parthjadhao/chess-ws:latest

      # -------- PRISMA / MIGRATE --------
      - name: Build & Push chess-migrate
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/db/Dockerfile
          push: true
          tags: parthjadhao/chess-migrate:latest
