name: Build and deploy to docker hub

on :
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

        # for chess frontend
      - name: Build and push docker image chess-frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/web/DockerFile
          push: true
          tags: parthjadhao/chess:latest

      - name: Verify pushed image
        run: docker pull parthjadhao/chess:latest

      - name: Build and push docker image chess-backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/web/DockerFile
          push: true
          tags: parthjadhao/chess:latest

      - name: Verify pushed image
        run: docker pull parthjadhao/chess:latest
